[project]
name = "sample-code-lasc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lotus-ai[file-extractor]>=1.1.2",
    "tqdm>=4.67.1",
]
